# For more see https://gohugo.io/content-management/menus/

main:                # sections in the website sidebar
  - identifier: home # section id
    name: Home       # section display title
    url: /           # path to the section
    weight: 1        # order of sections

  - identifier: about
    name: About
    url: /about/
    weight: 2

  - identifier: how-to
    name: How-to Guides
    url: /how-to
    weight: 3

  - identifier: courses
    name: Courses
    url: /courses
    weight: 4

  - identifier: search
    name: Search
    url: /search/
    weight: 5

  - identifier: tags
    name: Tags
    url: /tags
    weight: 6

  - identifier: github
    name: GitHub
    url: 'https://github.com/LouisLU9911'
    weight: 20
    params:
      external: true

feeds:
  - identifier: rss
    name: RSS 2.0
    url: /feeds/feed.rss.xml
    weight: 1
  - identifier: atom
    name: Atom
    url: /feeds/feed.atom.xml
    weight: 2
  - identifier: json
    name: Json Feed
    url: /feeds/feed.json
    weight: 3
