# Site description. Used in meta description
description: >-
  Louis LU's blog.

# SEO keywords. Used in 'meta name="keywords"' tag.
# May be overridden by .Keywords or .Tags in front matter.
keywords:
  - hugo
  - ed
  - hugo theme
  - minimal
  - responsive
  - clean
  - louislu9911
  - Louis LU

# A "copyright"-line to be added to RSS/Atom files.
# "&copy;" and "{year}" will be replaced by © and the current year.
copyright: 'Copyright &copy; 2023-{year} Louis LU'

# Colour scheme. Options: red, orange, magenta, cyan, blue, brown
colorScheme: ''

# Used in site header
tagline: From Dusk Till Dawn

# Custom footer text on left sidebar. Use HTMl if needed.
# "&copy;" and "{year}" will be replaced by © and the current year.
footer: >-
  Powered by <a href="https://gohugo.io">Hugo</a>. Built with <a href="https://github.com/sergeyklay/gohugo-theme-ed"
  target="_blank" rel="noopener noreferrer">Ed</a>. Distributed under an MIT
  license.

# Sections to be displayed in:
# - main page
# - RSS/Atom/Json feeds
# - search index
# - ...
mainSections:
  - how-to

# Posts date format, for example: 2006-01-02
dateFormat: ':date_long'
dateFormatToc: 2006.01.02

# Show "Read more" button in list if true
readmore: true

# RSS/Atom feed size
feedSize: 25

recentPostsSize: 5

contact:
  # No contact
  # Forms Backend URL, used in contacts form
  formAction: ''

  # Contact form email subject
  emailSubject: ''

  # Where should the user be redirected after successful form submit?
  thanksUrl: /thanks

# Site icons, relative to ./static
assets:
  # favicon.ico for legacy browsers
  favicon: /img/louislu-graph-logo.png

  # A single SVG icon with a light/dark version for modern browsers
  svgicon: /img/louislu-graph-logo.svg

  # 180×180 PNG image for Apple devices
  apple_touch_icon: /img/louislu-graph-logo-apple.png

  # Logo image, relative to ./assets
  logo: /img/louislu-graph-logo.png
  disable_fingerprinting: false

seo:
  # Will be used in schema.org/Organization.
  # The site.Title  will be used if empty.
  publisher: Louis LU

  # To anonymize the IP addresses of hits sent to Google Analytics
  # set this param to true. Please note, to enable Google Analytics
  # you have to set `googleAnalytics` param in config.yaml file.
  anonymizeIp: true

social:
  # Do not display social media account
  # Array of Facebook Page Admin IDs for Domain Insights
  facebookAdminIds: []

  # Facebook Page ID
  facebookId: ''

  # Twitter username for the website
  twitter: ''

# Configure search engine
search:
  # Maximum length (in words) of each text blurb. You can change this
  # value if you find that 100 is too short or too long for your taste.
  maxSummaryLength: 100
  # Lunr has full support for the indexing and searching of documents
  # in English. If your documents are in another language, uncomment
  # required languages below.
  # TODO: Add Chinese
  # For more see: https://lunrjs.com/guides/language_support.html
  languages:
    # - de
    - en
    - es
    # - fr
    # - it
    # - pt
    # - ru
